version: "3.8"

services:
  backend:
    build: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 5000
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "4173:4173"
